apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: default
spec:
  rules:
    - host: www.nginx.ctt
      http:
        paths:
          - backend:
              resource:
#                apiGroup: string
#                kind: string
#                name: string
              service:
                name: nginx-service
                port:
                  name: http

            path: /
            pathType: ImplementationSpecific
  tls:
#    - hosts:
#        - string
#      secretName: string
  backend:
    {}
#  defaultBackend:
#    resource:
#      apiGroup: string
#      kind: string
#      name: string
#    service:
#      name: string
#      port:
#        name: string
#        number: int
#  ingressClassName: string
__clone: true
cacheObject:
  useNestedBackendField: true
  showPathType: true
