apiVersion: v1
kind: Service
metadata:
  name: java-test-service
  labels:
    app: java-test
spec:
  type: ClusterIP
  selector:
    app: java-test
  ports:
  - port: 80
    protocol: TCP
    targetport: 8080
