apiVersion: v1
kind: Pod
spec:
  dnsConfig:
    nameservers:
      - 8.8.8.8
      - 8.8.4.4
  containers:
  - name: shell
    image: ubuntu
    command:
    - sleep
    args:
    - infinity
  - name: kubectl
    image: bitnami/kubectl
    command:
    - cat
    tty: true
  - name: docker
    image: docker:latest
    env:
       - name: DOCKER_OPTS
         value: '"--insecure-registry=rancher-ctt-eks-da7a779485cdcb9f.elb.ca-central-1.amazonaws.com"'
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
